import {
  Receipt,
  BarChart2,
  ShoppingBag,
  ShieldCheck,
  UtensilsCrossed,
  Eye,
} from "lucide-react";

export const roleTemplates = {
  store: [
    {
      key: "cashier",
      icon: Receipt,
      permissions: [
        "products_read",
        "categories_read",
        "orders_create",
        "orders_read",
        "orders_update",
        "payments_create",
        "payments_read",
        "tickets_read",
        "tickets_create",
      ],
    },
    {
      key: "seller",
      icon: ShoppingBag,
      permissions: [
        "products_read",
        "categories_read",
        "orders_create",
        "orders_read",
        "payments_create",
        "payments_read",
        "tickets_read",
        "tickets_create",
      ],
    },
    {
      key: "manager",
      icon: BarChart2,
      permissions: [
        "products_read",
        "products_create",
        "products_update",
        "categories_read",
        "categories_create",
        "categories_update",
        "orders_read",
        "orders_create",
        "orders_update",
        "orders_delete",
        "payments_read",
        "payments_create",
        "payments_update",
        "tickets_read",
        "tickets_create",
        "tickets_update",
        "users_read",
        "settings_read",
        "wallet_read",
      ],
    },
    {
      key: "admin",
      icon: ShieldCheck,
      isAdmin: true,
      permissions: [],
    },
  ],
  restaurant: [
    {
      key: "waiter",
      icon: UtensilsCrossed,
      permissions: [
        "dish_read",
        "orders_read",
        "orders_create",
        "orders_update",
        "tables_read",
        "tables_update",
        "spaces_read",
        "tickets_read",
        "tickets_create",
        "payments_read",
        "payments_create",
      ],
    },
    {
      key: "cashier",
      icon: Receipt,
      permissions: [
        "orders_read",
        "orders_update",
        "payments_read",
        "payments_create",
        "payments_update",
        "tickets_read",
        "tickets_create",
        "shifts_read",
        "shifts_create",
        "shifts_update",
        "reports_read",
      ],
    },
    {
      key: "supervisor",
      icon: Eye,
      permissions: [
        "dish_read",
        "orders_read",
        "orders_create",
        "orders_update",
        "orders_delete",
        "payments_read",
        "payments_create",
        "payments_update",
        "tables_read",
        "tables_update",
        "spaces_read",
        "tickets_read",
        "tickets_create",
        "tickets_update",
        "shifts_read",
        "shifts_create",
        "shifts_update",
        "reports_read",
        "users_read",
        "settings_read",
      ],
    },
    {
      key: "manager",
      icon: BarChart2,
      permissions: [
        "dish_read",
        "dish_create",
        "dish_update",
        "ingredients_read",
        "ingredients_create",
        "ingredients_update",
        "suppliers_read",
        "orders_read",
        "orders_create",
        "orders_update",
        "orders_delete",
        "payments_read",
        "payments_create",
        "payments_update",
        "tables_read",
        "tables_create",
        "tables_update",
        "spaces_read",
        "spaces_create",
        "tickets_read",
        "tickets_create",
        "tickets_update",
        "shifts_read",
        "shifts_create",
        "shifts_update",
        "reports_read",
        "reports_export",
        "users_read",
        "settings_read",
        "settings_update",
        "wallet_read",
      ],
    },
    {
      key: "admin",
      icon: ShieldCheck,
      isAdmin: true,
      permissions: [],
    },
  ],
};
