name: Client Unit Tests

on:
  pull_request:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - run: npm ci
        working-directory: ./client

      - run: npm audit --audit-level=high
        working-directory: ./client

      - run: npm test
        working-directory: ./client
